In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [30]:
arr = np.dstack([np.asarray([[1, 1, 1, 1], [2, 2, 2, 2]]), np.asarray([[3, 3, 3, 3], [4, 4, 4, 4]]), np.asarray([[5, 5, 5, 5], [6, 6, 6, 6]])])
print(arr)
b = np.asarray([[1, 1, 3, 1], [1, 1, 1, 1]])
arr = np.equal(arr, np.dstack([b for i in range(3)]))
print(arr)
print(np.sum(arr, axis=2))

[[[1 3 5]
  [1 3 5]
  [1 3 5]
  [1 3 5]]

 [[2 4 6]
  [2 4 6]
  [2 4 6]
  [2 4 6]]]
[[[ True False False]
  [ True False False]
  [False  True False]
  [ True False False]]

 [[False False False]
  [False False False]
  [False False False]
  [False False False]]]
[[1 1 1 1]
 [0 0 0 0]]


In [25]:
np.dstack([b for i in range(3)])

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])